steps:
- id: 'GIT DETAILS'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "$_BASE_BRANCH"
      echo "$_PR_NUMBER"
      echo "$_HEAD_BRANCH"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    cd envs/$_BASE_BRANCH
    ls
    terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd envs/$_BASE_BRANCH
    terraform plan -out=/workspace/plan.txt
# [END tf-plan]

# [Fetch GITHUB PAT] 
- id: 'Secret Manager'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [
      '-c',
      "gcloud secrets versions access latest --secret=Terraform-github-oauthtoken-529e72 --format='get(payload.data)' | tr '_-' '/+' | base64 -d > token.txt"
  ]
# [End Fetch GITHUB PAT]

# [Update GITHUB PR]
- id: 'PR Comment'
- name: 'gcr.io/cloud-builders/curl'
  args:
    - '-X'
    - 'POST'
    - '-H'
    - 'Authorization': token $PAT
    - '-H'
    - 'Accept: application/vnd.github.v3+json'
    - 'https://api.github.com/repos/${_REPO}/issues/${_PR_NUMBER}/comments'
    - '-d'
    - '{"body" : "HI"}'

# [End Update GITHUB PR]

availableSecrets:
  secretManager:
  - versionName: projects/exalted-kayak-429218-m7/secrets/Terraform-github-oauthtoken-529e72/versions/1
    env: 'PAT'
logsBucket: tf-vikki-625
serviceAccount: 865839242171-compute@developer.gserviceaccount.com
