steps:
- id: 'GIT DETAILS'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "$_BASE_BRANCH"
      echo "$_PR_NUMBER"
      echo "$_HEAD_BRANCH"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    cd envs/$_BASE_BRANCH
    ls
    terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd envs/$_BASE_BRANCH
    terraform plan -out=/workspace/plan.txt
# [END tf-plan]

# [Update GITHUB PR]
- id: 'PR Comment'
  name: 'gcr.io/cloud-builders/curl'
  secretEnv: ['PAT']
  args:
    - '-X'
    - 'POST'
    - '-H'
    - 'Authorization: token $$PAT'
    - '-H'
    - 'Accept: application/vnd.github.v3+json'
    - 'https://api.github.com/repos/vikki625/${_REPO}/pulls/comments/${_PR_NUMBER}'
    - '-d'
    - '{"body" : "HI"}'

# [End Update GITHUB PR]

availableSecrets:
  secretManager:
  - versionName: projects/exalted-kayak-429218-m7/secrets/git-pat/versions/1
    env: 'PAT'
logsBucket: tf-vikki-625
serviceAccount: 865839242171-compute@developer.gserviceaccount.com
