steps:
- id: 'GIT DETAILS'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "$_BASE_BRANCH"
      echo "$_PR_NUMBER"
      echo "$_HEAD_BRANCH"
      echo "$REPO_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    cd envs/$_BASE_BRANCH
    ls
    terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd envs/$_BASE_BRANCH
    terraform plan -out=/workspace/plan.txt
    cat /workspace/plan.txt
# [END tf-plan]

# [Update GITHUB PR]
- id: 'PR Comment'
  name: 'badouralix/curl-jq'
  entrypoint: 'sh'
  args:
  - '-c'
  - pr_title=$(curl -X GET -H "Authorization:Bearer $$PAT" -H 'Accept:application/vnd.github.v3+json' https://api.github.com/repos/vikki625/${REPO_NAME}/pulls/{_PR_NUMBER} | jq -r '.title')
  - echo "$pr_title"
  - curl -X PATCH -H "Authorization:Bearer $$PAT" -H 'Accept:application/vnd.github.v3+json' -H 'Content-Type:application/json' --data '$(jq -n --arg pr_title "$pr_title" --arg body "$(cat plan.txt)" '{"title":$pr_title,"body":$body,"state":"open","base":"dev"}')' https://api.github.com/repos/vikki625/terraform-cloud-build/pulls/1
  secretEnv: ['PAT']

# [End Update GITHUB PR]

availableSecrets:
  secretManager:
  - versionName: projects/exalted-kayak-429218-m7/secrets/git-pat/versions/2
    env: 'PAT'
logsBucket: tf-vikki-625
serviceAccount: 865839242171-compute@developer.gserviceaccount.com
