steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "envs/$BRANCH_NAME/" ]; then
        cd envs/$BRANCH_NAME
        ls
        terraform init
      else
        for dir in envs/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "envs/$BRANCH_NAME/" ]; then
        cd envs/$BRANCH_NAME
        terraform plan
      else
        for dir in envs/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFORM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "envs/$BRANCH_NAME/" ]; then
        cd envs/$BRANCH_NAME      
        #terraform apply -auto-approve
        echo "Branch '$BRANCH_NAME' for apply."
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an official environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]   

logsBucket: tf-vikki-625
serviceAccount: 865839242171-compute@developer.gserviceaccount.com